IF NOT EXISTS (
    SELECT 1 FROM sys.objects 
    WHERE object_id = OBJECT_ID(N'[dbo].[Sp_Insert_Notification_Category_Mapping]') 
    AND type = N'P'
)
BEGIN
    EXEC('
CREATE procedure [dbo].[Sp_Insert_Notification_Category_Mapping] 
@Role_Id bigint,
@NotificationCategory varchar(max),
@AutogeneratedCat_Id bigint,
@UserId bigint
AS
Declare @Status_Log varchar(100)
declare @StartCount bigint
Declare @TotalCount bigint
Declare @tempNotification_Id bigint
BEGIN
	if not exists(select distinct[Role_Id] from [dbo].Tbl_Notification_mapping where Role_id=@Role_Id and Notification_category=@NotificationCategory)
	begin
		set @Status_Log=''Inserted''
		insert into [dbo].Tbl_Notification_mapping (Role_id,Notification_category,AutoGenerateCategory_id) values(@Role_Id,@NotificationCategory,@AutogeneratedCat_Id)
	End
		--create table #Tbl(Id bigint PRIMARY KEY IDENTITY(1,1),notification_Id bigint)  
		--insert into #Tbl (notification_Id)
		--select Notification_Id from Tbl_Notifications where Category_Id=@AutogeneratedCat_Id
		--delete from Tbl_User_Notification_Mapping where UserId=@UserId
		--set @StartCount =1
		--set @TotalCount=(select Count(Id) from #Tbl)
		--while(@StartCount<=@TotalCount)
		--begin
		--set @tempNotification_Id=(select notification_Id from #Tbl where Id=@StartCount)
		--	if(not exists(select * from Tbl_User_Notification_Mapping where UserId=@UserId and RoleId=@Role_Id and NotificationId=@tempNotification_Id))
		--	begin
		--		if(exists(select Role_Id FROM dbo.Tbl_ACNR_Role_Notification_Category_Mapping where Role_Id=@Role_Id and NotificationCategory=@NotificationCategory))
		--		begin
		--			insert into Tbl_User_Notification_Mapping(RoleId,UserId,NotificationId,ReadUnreadStatus,CreatedDate,UpdatedDate,Message_Sent_Status)
		--			values(@Role_Id,@UserId,@tempNotification_Id,0,getdate(),getdate(),0)
		--		end
		--	end
		--set @StartCount=@StartCount+1
		--end
select @Status_Log
END

   ');
END;
