IF NOT EXISTS (
    SELECT 1 FROM sys.objects 
    WHERE object_id = OBJECT_ID(N'[dbo].[SP_OVERALL_ACTIVITY_Report_ALL]') 
    AND type = N'P'
)
BEGIN
    EXEC('
CREATE procedure [dbo].[SP_OVERALL_ACTIVITY_Report_ALL]

AS
BEGIN
select NEW_ENTROLLMENT_YEASTERADY ,NEW_ENTROLLMENT_MONTH ,NEW_ENTROLLMENT_YEAR ,NEW_ENQUIRY_YESTERDAY ,
   FOLLOW_UP_NOT_MONTH,FOLLOW_UP_CALL,SUM_OF_STUDENT ,ATT_NOT_UPDATED ,TOTAL_ARREAR ,PAID_YESTERDAY ,PAID_MONTH ,PAID_YEAR ,
   EXCESS,NUM_OF_STUDENT_DROP,TOT_FEE_ARREAR_CUR_MONTH,TOT_FEE_ARREAR_NON_CURRENT  FROM tbl_OverAllActivity_REPORT --where month=@month
 

 End
');
END