IF NOT EXISTS (
    SELECT 1 FROM sys.objects 
    WHERE object_id = OBJECT_ID(N'[dbo].[SP_Update_Candidate_ContactDet]') 
    AND type = N'P'
)
BEGIN
    EXEC('
CREATE procedure [dbo].[SP_Update_Candidate_ContactDet]
(@Candidate_Id bigint,@Candidate_PermAddress varchar(max),        
@Candidate_ContAddress varchar(max),@Candidate_Telephone varchar(50),@Candidate_Mob1 varchar(50),
@Candidate_Mob2 varchar(50),@Candidate_Email varchar(50),@Candidate_FatherName varchar(100),        
@Candidate_FatherOcc varchar(200),@Candidate_MotherName varchar(100),@Candidate_MotherOcc varchar(200),
@Candidate_Relationship varchar(100),        
@AddressLine2_Parent varchar(max),
@Address_City_Parent varchar(max),
@Address_state_Parent varchar(max),
@Address_res_country_Parent varchar(max),
@Addresspostcode_Parent varchar(max),
     
@Candidate_FatherEmail varchar(50),@Candidate_idNo varchar(50),    
@PostCode varchar(50),        
@FatherAddress  varchar(max),        
@FatherIcNo varchar(50),        
@FatherMobileNo varchar(50),        
@MotherAddress varchar(max),        
@MotherIcNo varchar(50),        
@MotherMobileNo varchar(50),        
@MotherEmail varchar(max),      
 @Emergency_Name varchar(max),      
 @Emergency_mobile varchar(max),      
 @Emergency_relation varchar(50),  
 @ParentCTC VARCHAR(50),
 @Candidate_FatherQualification varchar(200),
 @Candidate_MotherQualification  varchar(200),
 @Candidate_PermAddress_Line2  varchar(max),    
@Candidate_PermAddress_postCode  varchar(max),
@Candidate_PermAddress_Country BIGINT,
@Candidate_PermAddress_State     varchar(max),
@Candidate_PermAddress_City varchar(max),
@Candidate_ContAddress_Line2 varchar(max),
@Candidate_ContAddress_postCode varchar(max),
@Candidate_ContAddress_Country BIGINT,
@Candidate_ContAddress_State varchar(max),
@Candidate_ContAddress_City varchar(max),
@emr_ICpassport varchar(MAX),
                    @emrname varchar(MAX),
                    @emrRelationship varchar(MAX),
                    @emr_residance  varchar(MAX),
                    @emrmob  varchar(MAX),
                    @emremail varchar(MAX),
                    @emraddr1 varchar(MAX),
                    @emraddr2 varchar(MAX),
                    @emrpostcode varchar(MAX),
                    @emrcountry bigint,
                    @emrstate  varchar(MAX),
                    @emrcity varchar(MAX),
                    @emrcheckstatus bit ,

                    @Candidate_parentAddress2   varchar(MAX),
@Candidate_Post varchar(MAX),
@Candidate_Country  varchar(MAX),
@Candidate_Sate varchar(MAX),
@Candidate_City varchar(MAX),

@Guardian_Icpassport    varchar(MAX),
@Candidate_Guardian_Relationship    varchar(MAX),
@Candidate_Guardian_Address2    varchar(MAX),
@Candidate_Guardian_PostCode    varchar(MAX),
@Candidate_Guardian_Country varchar(MAX),
@Candidate_Guardian_State   varchar(MAX),
@Candidate_Guardian_City    varchar(MAX),
@Candidate_GuardianName varchar(100),
@Candidate_Guardian_Address varchar(max),
@Candidate_Guardian_Telephone varchar(50),
@Candidate_Guardian_Mob varchar(50),
@Candidate_Guardian_Email varchar(100)

 )        
        
        
         
AS        
BEGIN        
UPDATE Tbl_Candidate_ContactDetails        
SET        
Candidate_Id=@Candidate_Id,        
Candidate_PermAddress=@Candidate_PermAddress,        
Candidate_ContAddress=@Candidate_ContAddress,        
Candidate_Telephone=@Candidate_Telephone,        
Candidate_Mob1=@Candidate_Mob1,        
Candidate_Mob2=@Candidate_Mob2,        
Candidate_Email=@Candidate_Email,        
Candidate_FatherName=@Candidate_FatherName,        
Candidate_FatherOcc=@Candidate_FatherOcc,        
Candidate_MotherName=@Candidate_MotherName,        
Candidate_MotherOcc=@Candidate_MotherOcc,        
Candidate_GuardianName=@Candidate_GuardianName,        
Candidate_Relationship=@Candidate_Relationship,        
Candidate_Guardian_Address=@Candidate_Guardian_Address,        
Candidate_Guardian_Telephone=@Candidate_Guardian_Telephone,        
Candidate_Guardian_Mob=@Candidate_Guardian_Mob,        
Candidate_Guardian_Email=@Candidate_Guardian_Email,        
Candidate_FatherEmail=@Candidate_FatherEmail,     
Candidate_idNo=@Candidate_idNo,    
PostCode=@PostCode,        
FatherAddress=@FatherAddress,        
FatherIcNo=@FatherIcNo,        
FatherMobileNo=@FatherMobileNo,        
MotherAddress=@MotherAddress,        
MotherIcNo=@MotherIcNo,        
MotherMobileNo=@MotherMobileNo,        
MotherEmail=@MotherEmail,      
 Emergency_Name=@Emergency_Name,      
 Emergency_mobile=@Emergency_mobile,      
 Emergency_relation=@Emergency_relation,  
 ParentCTC=@ParentCTC,
 Candidate_FatherQualification=@Candidate_FatherQualification,
 Candidate_MotherQualification=@Candidate_MotherQualification,
 Candidate_PermAddress_Line2=@Candidate_PermAddress_Line2,  
Candidate_PermAddress_postCode=@Candidate_PermAddress_postCode,
Candidate_PermAddress_Country=@Candidate_PermAddress_Country,
Candidate_PermAddress_State=@Candidate_PermAddress_State,   
Candidate_PermAddress_City=@Candidate_PermAddress_City,
Candidate_ContAddress_Line2=@Candidate_ContAddress_Line2,
Candidate_ContAddress_postCode=@Candidate_ContAddress_postCode,
Candidate_ContAddress_Country=@Candidate_ContAddress_Country,
Candidate_ContAddress_State=@Candidate_ContAddress_State,
Candidate_ContAddress_City=@Candidate_ContAddress_City,
Emergency_Parent_IcpassportNo=@emr_ICpassport,
Emergency_Name1=@emrname,
Emergency_Relationship=@emrRelationship,
Emergency_Mob=@emrmob,
Emergency_Telephone=@emr_residance,
Emergency_Mail=@emremail,
Emergency_Address1=@emraddr1,
Emergency_Address2=@emraddr2,
Emergency_Postcode=@emrpostcode,
Emergency_Country=@emrcountry,
Emergency_State=@emrstate,
Emergency_City=@emrcity,
Emergency_Check_Status=@emrcheckstatus ,

Candidate_parentAddress2=@Candidate_parentAddress2,
Candidate_Post=@Candidate_Post,
Candidate_Country=@Candidate_Country,
Candidate_Sate=@Candidate_Sate,
Candidate_City=@Candidate_City,
--Candidate_PermAddress_Line2=@AddressLine2_Parent,
--Candidate_PermAddress_postCode=@Addresspostcode_Parent,
--Candidate_PermAddress_State=@Address_state_Parent,
--Candidate_PermAddress_City=@Address_City_Parent,
--Candidate_PermAddress_Country=@Address_res_country_Parent
Guardian_Icpassport=@Guardian_Icpassport,
Candidate_Guardian_Relationship=@Candidate_Guardian_Relationship,
Candidate_Guardian_Address2=@Candidate_Guardian_Address2,
Candidate_Guardian_PostCode=@Candidate_Guardian_PostCode,
Candidate_Guardian_Country=@Candidate_Guardian_Country,
Candidate_Guardian_State=@Candidate_Guardian_State,
Candidate_Guardian_City=@Candidate_Guardian_City


WHERE @Candidate_Id=Candidate_Id        
        
END     
    ')
END;
