IF NOT EXISTS (
    SELECT 1 
    FROM sys.objects 
    WHERE object_id = OBJECT_ID(N'[dbo].[SP_Update_Candidate_ContactDet_Otherstab]') 
    AND type = N'P'
)
BEGIN
    EXEC('
CREATE procedure [dbo].[SP_Update_Candidate_ContactDet_Otherstab]
(
@Candidate_Id bigint,
@ParentICPassport varchar(MAX),
@Candidate_FatherName varchar(MAX),
@Candidate_Relationship varchar(MAX),
@Candidate_ParentMob varchar(MAX),
@Candidate_Residancephone varchar(MAX),
@Candidate_FatherEmail varchar(MAX),
@AddressLine1_Parent varchar(MAX),
@Candidate_ParentAddress2 varchar(MAX),
@Candidate_Post varchar(MAX),
@Candidate_Country varchar(MAX),
@Candidate_Sate varchar(MAX),
@Candidate_City varchar(MAX),
@Emergency_ICPassport varchar(MAX),
@Emergency_Name varchar(MAX),
@Emergency_Relation varchar(MAX),
@Emergency_Mob varchar(MAX),
@Emergency_Telephone varchar(MAX),
@Emergency_Mail varchar(MAX),
@Emergency_Address1 varchar(MAX),
@Emergency_Address2 varchar(MAX),
@Emergency_Postcode varchar(MAX),
@Emergency_Country varchar(MAX),
@Emergency_State varchar(MAX),
@Emergency_city varchar(MAX),
@emrcheckstatus  varchar(MAX),
@Guardian_Icpassport varchar(MAX),
@Candidate_GuardianName varchar(MAX),
@Candidate_Guardian_Relationship varchar(MAX),
@Candidate_Guardian_Mob varchar(MAX),
@Candidate_Guardian_Telephone varchar(MAX),
@Candidate_Guardian_Email varchar(MAX),
@Candidate_Guardian_Address varchar(MAX),
@Candidate_Guardian_Address2 varchar(MAX),
@Candidate_Guardian_PostCode varchar(MAX),
@Candidate_Guardian_Country varchar(MAX),
@Candidate_Guardian_State varchar(MAX),
@Candidate_Guardian_City varchar(MAX),
@sibilings varchar(MAX),
@brothers varchar(MAX),
@age varchar(MAX),
@sister varchar(MAX),
@sister_age varchar(MAX),
@tongue varchar(MAX),
@hobby varchar(MAX),
@language varchar(MAX),
@householdIncome varchar(100),
@GOccupation varchar(100),
@GCompany varchar(100),
@GSalRange varchar(100),
@FatherOccu varchar(100),
@PCompany varchar(100),
@PSalRange varchar(100),
@depententVisa varchar(100),
@parentTelegram varchar(100),
@otherMemberName varchar(50),
@noOfDep varchar(20)=''''
)        
         
AS        
BEGIN        
UPDATE Tbl_Candidate_ContactDetails        
SET        

ICPassport=@ParentICPassport,
Candidate_idNo=@ParentICPassport,
Candidate_FatherName=@Candidate_FatherName,
Candidate_Relationship=@Candidate_Relationship,
fatherMobileNo=@Candidate_ParentMob,
Candidate_Parent_Landline=@Candidate_Residancephone,
Candidate_FatherEmail=@Candidate_FatherEmail,
FatherICNo=@AddressLine1_Parent,
Candidate_ParentAddress2=@Candidate_ParentAddress2,
Candidate_Post=@Candidate_Post,
Candidate_Country=@Candidate_Country,
Candidate_Sate=@Candidate_Sate,
Candidate_City=@Candidate_City,
Emergency_Parent_ICpassportNo=@Emergency_ICPassport,
Emergency_Name1=@Emergency_Name,
Emergency_Name=@Emergency_Name,
Emergency_Relation=@Emergency_Relation,
Emergency_mobile=@Emergency_Mob,
Emergency_Mob=@Emergency_Mob,
Emergency_Telephone=@Emergency_Telephone,
Emergency_Mail=@Emergency_Mail,
Emergency_Address1=@Emergency_Address1,
Emergency_Address2=@Emergency_Address2,
Emergency_Postcode=@Emergency_Postcode,
Emergency_Country=@Emergency_Country,
Emergency_State=@Emergency_State,
Emergency_city=@Emergency_city,
Emergency_Check_Status=@emrcheckstatus ,
Guardian_Icpassport=@Guardian_Icpassport,
Candidate_GuardianName=@Candidate_GuardianName,
Candidate_Guardian_Relationship=@Candidate_Guardian_Relationship,
Candidate_Guardian_Mob=@Candidate_Guardian_Mob,
Candidate_Guardian_Telephone=@Candidate_Guardian_Telephone,
Candidate_Guardian_Email=@Candidate_Guardian_Email,
Candidate_Guardian_Address=@Candidate_Guardian_Address,
Candidate_Guardian_Address2=@Candidate_Guardian_Address2,
Candidate_Guardian_PostCode=@Candidate_Guardian_PostCode,
Candidate_Guardian_Country=@Candidate_Guardian_Country,
Candidate_Guardian_State=@Candidate_Guardian_State,
Candidate_Guardian_City=@Candidate_Guardian_City,
sibilings=@sibilings,
brothers=@brothers,
age=@age,
sister=@sister,
sister_age=@sister_age,
tongue=@tongue,
language=@language,
hobby=@hobby,
ParentCTC=@householdIncome,
GuardianOccupation=@GOccupation,
GuardianCompanyName =@GCompany,
GuardSalaryRange=@GSalRange,
Candidate_FatherOcc=@FatherOccu,
ParentCompanyName=@PCompany,
ParentSalaryRange=@PSalRange,
DependentVisa=@depententVisa,
ParentTelegramUserName=@parentTelegram,
OtherMemberName=@otherMemberName,
NoOfDependents=@noOfDep

WHERE @Candidate_Id=Candidate_Id        
        
END
    ')
END
